server:
  port: 8090           # 配置访问端口
  servlet:
    encoding:
      force: true      # 配置使用 UTF-8 编码
      charset: UTF-8

spring:
  application:
    name: simple-spring-boot-mybatis-plus-template  # 配置项目名
  web:
    locale: zh_CN
    locale-resolver: accept_header
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss  # LocalDateTime、OffsetDateTime、ZonedDateTime
      date: yyyy-MM-dd                # LocalDate
      time: HH:mm:ss                  # LocalTime、OffsetTime
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5s
  session:
    store-type: redis
    timeout: 4h
  data:
    redis:
      repositories:
        enabled: false

user:
  session:
    header: Auth-Token
    maxOnlineUser: 1

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  type-aliases-package: cn.dev666.simple.template.obj.model
  mapper-locations: classpath*:**/*Mapper.xml

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true